import "./globals.css";

export const metadata = {
  title: "La Petite Boutique D'Ephee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className="bg-background-500 overflow-x-hidden">
      <link
        rel="apple-touch-icon"
        sizes="180x180"
        href="/assets/favicon/apple-touch-icon.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="/assets/favicon/favicon-32x32.png"
      />
      <link
        rel="shortcut icon"
        href="/assets/favicon/favicon.ico"
        type="image/x-icon"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="16x16"
        href="/assets/favicon/favicon-16x16.png"
      />
      <body className="overflow-x-hidden">{children}</body>
    </html>
  );
}
